apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-training
  template:
    metadata:
      labels:
        app: llm-training
    spec:
      containers:
      - name: llm-training
        image: huggingface/transformers-pytorch-gpu:latest
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
        command: ["python", "train.py", "--deepspeed", "ds_config.json"]
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: llm-training-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: llm-training
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
