
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloom-sentiment-azure
  namespace: model-serving
  labels:
    app: bloom-sentiment
    cloud: azure
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bloom-sentiment
      cloud: azure
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: bloom-sentiment
        cloud: azure
    spec:
      containers:
      - name: model-server
        image: xnlacr.azurecr.io/bloom-sentiment:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
            nvidia.com/gpu: 1
          limits:
            memory: "16Gi"
            cpu: "4"
            nvidia.com/gpu: 1
        env:
        - name: DEPLOYMENT_CLOUD
          value: "AZURE"
        - name: MODEL_PATH
          value: "/models/bloom-finetuned-sentiment"
        volumeMounts:
        - name: model-storage
          mountPath: /models
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc-azure
